version: '3.8'

services:
  web:
    build: .
    image: kaira_web_image
    container_name: kaira_web_container
    ports:
      - "8778:8778"
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - DEBUG=False
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=turdalihasanboyev144@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=123
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py createsuperuser --noinput || true &&
             python manage.py runserver 0.0.0.0:8778"
